services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: cash-app-prod
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    command: ["/entrypoint.sh"]

  nginx:
    image: nginx:alpine
    container_name: cash-app-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app