services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/app
    networks:
      - cash-app-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cash-app-network

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cash_app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3306
    volumes:
      - db_dev_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - cash-app-network

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - cash-app-network

networks:
  cash-app-network:
    driver: bridge

volumes:
  db_dev_data:
    driver: local