services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    extra_hosts:
      - "app.local:host-gateway"
    volumes:
      - ./:/app
    networks:
      - cash-app-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cash-app-network

networks:
  cash-app-network:
    driver: bridge
