services:
  app_cash:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - DATABASE_URL=mysql://root:password@db:3306/cash_app
      - NUXT_SESSION_PASSWORD=f904b3335c0c4a67916a7f281c07429e
    networks:
      - cash-app-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_cash.rule=Host(`${WEB_URL}`)"
      - "traefik.http.routers.app_cash.entrypoints=websecure"
      - "traefik.http.routers.app_cash.tls.certResolver=letsencrypt"
      - "traefik.http.services.app_cash.loadbalancer.server.port=3000"

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cash_app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3306
    volumes:
      - db_dev_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - cash-app-network

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - cash-app-network

networks:
  cash-app-network:
    driver: bridge

volumes:
  db_dev_data:
    driver: local
  dokploy-network:
    external: true
