FROM nginx:alpine

RUN apk add --no-cache openssl

RUN mkdir -p /etc/nginx/ssl

RUN cat > /etc/nginx/ssl/openssl-san.cnf <<EOF
[ req ]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_req

[ dn ]
C  = FR
ST = IDF
L  = Paris
O  = Hiboo
CN = app.local

[ v3_req ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = app.local
EOF

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout /etc/nginx/ssl/nginx-selfsigned.key \
  -out /etc/nginx/ssl/nginx-selfsigned.crt \
  -config /etc/nginx/ssl/openssl-san.cnf \
  -extensions v3_req
